lojaapp/urls.py
from django.urls import path
from.views import *



app_name="lojaapp"
urlpatterns=[
    path("",HomeView.as_view(),name="home"),
    path("sobre/",SobreView.as_view(),name="sobre"),
    path("contato/",ContatoView.as_view(),name="contato"),
    path("todos-produtos/",TodosProdutosView.as_view(),name="Todosprodutos"),
    path("produto/<slug:slug>",ProdutoDetalheView.as_view(),name="produtodetalhe"),
    path("addcarro-<int:pro_id>/",AddCarroView.as_view(),name="addcarro"),
    
]

lojaproject/urls.py

from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("lojaapp.urls")),
]

urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

lojaapp/models.py
from django.db import models
from django.contrib.auth.models import User

class Cliente(models.Model):
    user= models.OneToOneField(User,on_delete=models.CASCADE)
    nome_completo= models.CharField(max_length=200)
    endereco=models.CharField(max_length=200,null=True,blank=True)
    data_on=models.DateField(auto_now_add=True)
    
    def __str__(self):
        return self.nome_completo

class Categoria(models.Model):
    titulo= models.CharField(max_length=200)
    slug= models.SlugField(unique=True)

    def __str__(self):
        return self.titulo

class Produto(models.Model):
    titulo= models.CharField(max_length=200)
    slug= models.SlugField(unique=True)
    categoria= models.ForeignKey(Categoria,on_delete=models.CASCADE)
    image= models.ImageField(upload_to="produtos")
    preco_mercado= models.PositiveIntegerField()
    venda= models.PositiveIntegerField()
    descricao= models.TextField()
    garantia= models.CharField(max_length=300,null=True,blank=True)
    return_devolucao= models.CharField(max_length=300,null=True,blank=True)
    visualizacao= models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.titulo
    

class Carro(models.Model):
    cliente= models.ForeignKey(Cliente,on_delete=models.SET_NULL,null=True,blank=True)
    total=models.PositiveIntegerField(default=0)
    criado_em=models.DateField(auto_now_add=True)

    def __str__(self):
        return "Carro:" + str(self.id)
        
class CarroProduto(models.Model):
        carro = models.ForeignKey(Carro,on_delete=models.CASCADE)
        produto=models.ForeignKey(Produto,on_delete=models.CASCADE)
        avaliacao=models.PositiveIntegerField()
        quantidade=models.PositiveIntegerField()
        subtotal=models.PositiveIntegerField()
        def __str__(self):
            return "Carro:" + str(self.carro.id)+"CarroProduto:"+ str(self.id)
PEDIDO_STATUS=(
     ("Pedido Recebido","Pedido Recebido"),
     ("Pedido Processando","Pedido Processando"),
     ("Pedido Caminho","Pedido Caminho"),
     ("Pedido Completado","Pedido Completado"),
     ("Pedido Cancelado","Pedido Cancelado"),
)
class Pedido_order(models.Model):
        carro = models.OneToOneField(Carro,on_delete=models.CASCADE)

        ordenando_por=models.CharField(max_length=200)

        endereco_envio=models.CharField(max_length=200)
        telefone=models.CharField(max_length=10)
        email=models.EmailField(null=True,blank=True)
        subtotal=models.PositiveIntegerField()
        desconto=models.PositiveIntegerField()
        total=models.PositiveIntegerField()
        pedido_status=models.CharField(max_length=50,choices=PEDIDO_STATUS)
        criado_em=models.DateTimeField(auto_now_add=True)

        def __str__(self):
            return "Pedido_order:" + str(self.id)

lojaapp/views.py

from django.shortcuts import render
from django.views.generic import TemplateView
from.models import*



class HomeView(TemplateView):
    template_name = "home.html"
    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        context['produto_list']=Produto.objects.all().order_by("-id")
        return context
    
class TodosProdutosView(TemplateView):
    template_name = "todosprodutos.html"
    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        context['todoscategorias']=Categoria.objects.all()
        return context
    
class ProdutoDetalheView(TemplateView):
    template_name = "produtodetalhe.html"

    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        url_slug=self.kwargs['slug']
        produto=Produto.objects.get(slug=url_slug)
        produto.visualizacao +=1
        produto.save()
        context['produto']=produto
        return context
    
class AddCarroView(TemplateView):
    template_name = "addprocarro.html"
    
    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        produto_id=self.kwargs['pro_id']
        produto_obj=Produto.objects.get(id=produto_id)
        carro_id=self.request.session.get(carro_id,None)
        if carro_id:
            carro_obj=Carro.objects.get(id=carro_id)
        else:
            carro_obj=Carro.objects.create(total=0)
            self.request.session['carro_id']=carro_obj.id


         
    
    

class SobreView(TemplateView):

    template_name = "sobre.html"

class ContatoView(TemplateView):

    template_name = "contato.html"


templates/addprocarro.html
{% extends 'base.html' %}
{% block title%}Carrinho{%endblock%}
{% block content %}

<div class="container">
    produto adicionado no carrinho

</div>
    
    
    {% endblock content %}
    

templates/base.html

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title%}{%endblock%}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
</head>
<body>
    <a href="{% url 'lojaapp:home'%}">HOME</a>
    <a href="{% url 'lojaapp:sobre'%}">Sobre a Cidisa</a>
    <a href="{% url 'lojaapp:contato'%}">Contato da Cidisa</a>
    <a href="{% url 'lojaapp:Todosprodutos'%}">CATEGORIAS</a>
    <hr>
    
    
    {% block content %}

    {% endblock  %}
    
</body>
</html>

templates/contato.html
{% extends 'base.html' %}
{% block title%}Contato{%endblock%}
{% block content %}
<h1 class="text-center">Bem vindo a página Contato</h1>
    
    
    {% endblock  %}
    
    

templates/home.html
{% extends 'base.html' %}
{% block title%}Home{%endblock%}


{% block content %}

<div class="container">
    <h1 class="text-center">Bem vindo a página home</h1>
    <hr>
    
<div class="row mt-3">
    {% for p in produto_list%}
<div class="col-md-4">
    <div class="m-4">
        <h4>{{p.titulo}}</h4>
        <img src="{{p.image.url}}" alt="" class="img-fluid"style="height:100px; object-fit:cover;">
        <p class="mt-3">Preço: ,<strike>R$.{{p.preco_mercado}}</strike> R$.{{p.venda}}</p>
        <a href="{% url 'lojaapp:addcarro' p.id %}"class="btn btn-success">Comprar</a>
    </div>
</div>
{%endfor%}
</div>
    

</div>

    {%endblock%} 

   

templates/produtodetalhe.html
{% extends 'base.html' %}
{% block title%}{{produto.titulo}}{%endblock%}


{% block content %}

<div class="container">
    <h4>Produto:{{produto.titulo}}</h4><hr>
    <div class="row">
        <div class="col-md-6">
            <img src="{{produto.image.url}}" alt="" class="img-fluid" width="380px">

        </div>
        <div class="col-md-6" text-left>
            <h3>{{produto.titulo}}( {{produto.visualizacao}} Visualizações)</h3>
            <h4>Categoria:{{produto.categoria}}</h4>
            <h5>Preco:<strike>R$. {{produto.preco_mercado}}</strike> R$. {{produto.venda}}</h5>
            <a href="{% url 'lojaapp:addcarro' produto.id %}" class="btn btn-success">Comprar</a><hr>
            <p class="text-danger">Garantia : {{produto.garantia}}</p>
            <p class="text-danger">Politica de Devolucao : {{produto.return_devolucao}}</p><hr>
            <p class="text-sucess">{{produto.descricao}}</p>

        </div>
    </div>
           
</div>   
    
  
   {%endblock%} 

   

templates/sobre.html
{% extends 'base.html' %}
{% block title%}Sobre{%endblock%}
{% block content %}

<h1 class="text-center">Bem vindo a página Sobre</h1>
    
    
    {% endblock  %}
    

templates/todosprodutos.html
{% extends 'base.html' %}
{% block title%}TODOS PRODUTOS{%endblock%}


{% block content %}

<div class="container">
    <h4>TODOS OS PRODUTOS DA CATEGORIA</h4>

    {% for cat in todoscategorias %}

    <h1>{{cat.titulo}}</h1>
    <div class="row mt-3">
        {% for p in cat.produto_set.all%}
    <div class="col-md-4">
        <div class="m-4">
            <h4><a href="{% url 'lojaapp:produtodetalhe' p.slug %}"> {{p.titulo}}</a></h4>
            <img src="{{p.image.url}}" alt="" class="img-fluid"style="height:100px; object-fit:cover;">
            <p class="mt-3">Preço: ,<strike>R$.{{p.preco_mercado}}</strike> R$.{{p.venda}}</p>
            <a href="{% url 'lojaapp:addcarro' p.id %}"class="btn btn-success">Comprar</a>
        </div>
    </div>
    {%endfor%}
    </div>
        
    
    {%endfor%} 
</div>

    {%endblock%} 

   